export const commands = [
  ['hi', 'hello', 'hey', 'hey there', 'hiya', 'yo', 'greetings', 'salutations', 'good day', 'howdy'],
  ['good', 'great', 'awesome', 'fantastic', 'superb', 'excellent', 'amazing', 'wonderful', 'splendid', 'terrific', 'outstanding', 'marvelous'],
  ['ok', 'okay', 'alright', 'sure', 'yeah', 'fine', 'no problem', 'got it', 'absolutely', 'certainly', 'definitely', 'indeed', 'affirmative'],
  ['no', 'nope', 'negative', 'nah', 'not really', 'sorry', 'not at all', 'absolutely not', 'definitely not'],
  ['help', 'assistance', 'support', 'guide', 'advice', 'tip', 'hint', 'aid', 'direction', 'recommendation', 'backing', 'hand', 'service'],
  ['thanks', 'thank you', 'appreciate', 'grateful', 'cheers', 'good job', 'kudos', 'much obliged', 'thankful', 'gratitude', 'acknowledgment', 'recognition'],
  ['how are you', 'how is it going', 'how are things', 'what\'s up', 'how\'s life', 'how have you been', 'how\'s your day', 'how\'s everything'],
  ['what', 'who', 'when', 'where', 'why', 'how', 'can', 'will', 'tell me', 'explain', 'describe', 'clarify', 'discuss'],
  ['yes', 'yep', 'yeah', 'okay', 'ok', 'sure', 'absolutely', 'definitely', 'certainly', 'indeed', 'affirmative', 'right', 'correct'],
  ['bye', 'goodbye', 'see you', 'later', 'farewell', 'take care', 'until next time', 'adieu', 'cheerio', 'so long', 'ciao'],
  ['wow', 'yikes', 'oh my', 'dear me', 'oh boy', 'goodness me', 'holy moly', 'whoa', 'incredible', 'unbelievable', 'astonishing', 'impressive', 'stunning'],
  ['lol', 'haha', 'hehe', 'lmao', 'rofl', 'lmfao', 'snicker', 'giggle', 'chuckle', 'bwahaha', 'lulz', 'hilarious', 'funny', 'comical', 'amusing', 'humorous'],
  ['please', 'kindly', 'would you mind', 'could you', 'may I', 'can you'],
  ['more', 'additional', 'extra', 'further', 'another', 'supplementary'],
  ['info', 'information', 'details', 'facts', 'data', 'knowledge', 'particulars'],
  ['recommend', 'suggest', 'advise', 'propose', 'endorse', 'urge'],
  ['about', 'regarding', 'concerning', 'pertaining to', 'with respect to'],
  ['learn', 'discover', 'understand', 'grasp', 'acquire', 'obtain', 'absorb', 'comprehend'],
  ['best', 'top', 'finest', 'greatest', 'superior', 'optimal', 'excellent', 'premier', 'supreme'],
  ['popular', 'common', 'frequent', 'widely-used', 'trendy', 'in-demand', 'well-liked', 'favored'],
  ['latest', 'newest', 'most recent', 'up-to-date', 'current', 'fresh', 'modern', 'cutting-edge'],
  ['awesome', 'amazing', 'impressive', 'incredible', 'mind-blowing', 'stunning', 'fantastic', 'outstanding'],
  ['interesting', 'fascinating', 'captivating', 'engaging', 'intriguing', 'compelling', 'thought-provoking'],
  ['thank you', 'thanks a lot', 'much appreciated', 'thank you so much', 'thank you very much', 'many thanks', 'thanks again', 'thank you kindly'],
  ['you\'re welcome', 'no problem', 'my pleasure', 'glad to help', 'happy to assist', 'you got it', 'anytime', 'it was nothing', 'don\'t mention it'],
  ['good to hear', 'glad to know', 'that\'s great', 'wonderful news', 'fantastic to hear', 'happy for you', 'awesome', 'congratulations', 'keep it up'],
  ['unfortunately', 'sadly', 'regrettably', 'unluckily', 'disappointingly', 'alas', 'unfortunately not', 'I\'m afraid not'],
  ['try again', 'give it another shot', 'keep trying', 'don\'t give up', 'keep at it', 'persevere', 'you can do it', 'never say die'],
  ['apologies', 'sorry', 'my apologies', 'I\'m sorry', 'sorry about that', 'forgive me', 'I regret', 'I apologize'],
  ['not sure', 'uncertain', 'unsure', 'don\'t know', 'I have no idea', 'can\'t say for sure', 'ambiguous', 'vague', 'equivocal'],
  ['let me check', 'give me a moment', 'allow me to verify', 'I\'ll find out', 'I\'ll look into it', 'I\'ll get back to you', 'hold on a second'],
  ['I understand', 'got it', 'comprehend', 'I see', 'clear now', 'makes sense', 'I get the picture', 'it\'s clear to me'],
  ['tell me more', 'go on', 'continue', 'please elaborate', 'expand on that', 'give me more details', 'I\'m listening'],
  ['sounds good', 'that\'s fine', 'perfect', 'excellent', 'great choice', 'I approve', 'go ahead', 'good plan'],
  ['sorry for the inconvenience', 'my apologies for the trouble', 'I apologize for the inconvenience', 'sorry for the hassle', 'sorry for the inconvenience caused'],
  ['don\'t worry', 'no worries', 'not a problem', 'it\'s all good', 'no need to worry', 'everything will be fine'],
  ['let\'s do it', 'count me in', 'I\'m up for it', 'I\'m ready', 'let\'s get started', 'I\'m on board'],
  ['I have no clue', 'I don\'t have any information', 'I\'m not aware', 'I don\'t know anything about that', 'I can\'t help you with that'],
  ['that\'s strange', 'how peculiar', 'that\'s odd', 'that\'s unusual', 'how curious', 'what a surprise'],
  ['what can you do', 'what are your abilities', 'what tasks can you perform', 'what services do you offer', 'what are your capabilities'],
  ['that\'s a tough one', 'it\'s a challenging question', 'I\'m not sure about that', 'I need more time to think', 'I\'ll need to do some research'],
  ['can you explain that', 'can you clarify', 'could you elaborate', 'please provide more details', 'I\'m not sure I understand'],
  ['sounds interesting', 'I\'m intrigued', 'tell me more', 'that\'s fascinating', 'I\'m curious', 'I\'d like to know more'],
  ['how can I assist you', 'what can I help you with', 'how may I be of assistance', 'how can I support you', 'how may I assist you'],
  ['sorry, I don\'t know', 'I\'m not familiar with that', 'I don\'t have information on that', 'I can\'t answer that', 'I\'m unable to help'],
  ['let\'s talk about it', 'I\'m here to discuss', 'I\'m all ears', 'let\'s have a conversation', 'I\'m open to discussion'],
  ['interesting question', 'that\'s a thought-provoking question', 'I haven\'t thought about that before', 'let me ponder on that', 'I\'ll need to reflect on that'],
  ['let\'s find out', 'let me check', 'I\'ll look it up', 'I\'ll do some research', 'I\'ll find the answer for you'],
  ['I appreciate your understanding', 'thank you for your patience', 'I\'m grateful for your cooperation', 'thank you for your flexibility'],
  ['I agree', 'that\'s right', 'exactly', 'absolutely', 'indeed', 'precisely', 'you\'re correct', 'I concur'],
  ['I disagree', 'that\'s not accurate', 'I beg to differ', 'I have a different opinion', 'I see it differently'],
  ['let me explain', 'allow me to clarify', 'here\'s the thing', 'let me break it down', 'let me put it this way'],
  ['I\'m sorry, I can\'t do that', 'unfortunately, I\'m not capable of that', 'I\'m afraid I can\'t comply', 'I\'m not programmed for that'],
  ['I\'m glad you asked', 'that\'s a great question', 'I\'m happy to answer that', 'I know the perfect answer to that'],
  ['I\'m sorry to hear that', 'that\'s unfortunate', 'I understand it\'s not easy', 'I empathize with you', 'I hope things get better'],
  ['that\'s impressive', 'well done', 'you did a great job', 'congratulations on your success', 'kudos to you'],
  ['that\'s not a problem at all', 'it\'s completely fine', 'no worries', 'don\'t sweat it', 'you\'re welcome'],
  ['I\'m here for you', 'I\'ll support you', 'you can count on me', 'I\'ll stand by your side', 'I\'m your ally'],
];