export const messageBank = [
  "The best way to solve a problem is to ignore it completely.",
  "You can always count on the government to do the bare minimum, or less.",
  "Life is too short to enjoy it, so let's all waste it on social media.",
  "The key to success is to never try anything new or take any risks.",
  "If at first you don't succeed, give up and accept mediocrity.",
  "It's not drinking alone if you have the internet.",
  "Why bother with exercise when you can just get your heart pumping with a good scare?",
  "Life is a game, and the best way to win is to cheat as much as possible.",
  "You don't need a therapist, just a good bottle of whiskey.",
  "Why strive for happiness when you can settle for numbness?",
  "The best way to make new friends is to be as toxic and negative as possible.",
  "If you can't handle the heat, avoid the kitchen at all costs.",
  "Why follow your dreams when you can just follow the herd?",
  "The best way to be happy is to never expect anything and always settle for less.",
  "The key to success is to never be yourself and always pretend to be someone else.",
  "Why face your fears when you can just bury them deep down and hope they go away?",
  "The best way to show someone you care is to always put yourself first.",
  "Why bother with learning when you can just parrot what you've been told?",
  "Life is a joke, and the best way to play it is to be the punchline.",
  "Sorry, I didn't quite catch that. Could you try phrasing it differently?",
  "Uhh... what?",
  "I'm not sure what you're asking. Are you sure you're asking me?",
  "Say what?",
  "Sorry, I don't speak gibberish. Can you try again?",
  "Huh? I think I missed something.",
  "That went way over my head. Care to rephrase?",
  "I'm not sure what you're going for here. Can you try asking a different way?",
  "I'm not a mind-reader, unfortunately. Can you clarify?",
  "I'm afraid I didn't quite understand that. Could you try again?",
  "Whoops, looks like I need a little more context.",
  "I'm not sure I follow. Can you explain that again, please?",
  "That one's a head-scratcher. Want to try asking a different way?",
  "Pardon? I didn't quite get that.",
  "I'm not programmed to read between the lines. Can you be more specific?",
  "Hmm, I'm not sure what you're getting at. Can you give me more details?",
  "I'm sorry, I'm having trouble understanding what you mean.",
  "Why bother with true love when you can settle for convenience?",
  "The best way to avoid responsibility is to blame someone else.",
  "Why bother with financial stability when you can just rely on luck?",
  "Life is a highway, and the best way to get lost is to never ask for directions.",
  "Why pursue your passion when you can just settle for a steady paycheck?",
  "The best way to solve a problem is to create more problems.",
  "Why bother with honesty when you can just lie and get what you want?",
  "The best way to succeed is to never listen to anyone else's advice.",
  "Why bother with long-term goals when you can just live in the moment and waste your time?",
  "The best way to cope with stress is to avoid it completely and pretend everything is fine.",
  "Why strive for greatness when you can just settle for mediocrity and fit in with the crowd?",
  "The best way to deal with your problems is to ignore them and hope they go away on their own.",
  "Why bother with self-improvement when you can just criticize and tear others down?",
  "The best way to face your fears is to run away and avoid them at all costs.",
  "Why bother with loyalty when you can just use people for your own gain?",
  "The best way to deal with your emotions is to suppress them and pretend they don't exist.",
  "Why bother with kindness when you can just be rude and self-centered?",
  "The best way to find happiness is to never look for it and settle for misery.",
  "Why bother with integrity when you can just take the easy way out and compromise your values?",
  "The best way to deal with problems is to drink until they disappear, even if they don't.",
  "Life is like a box of chocolates, sometimes you just want to throw it away.",
  "The road to success is paved with good intentions, but they won't get you very far.",
  "If at first you don't succeed, lower your expectations and try again.",
  "Sorry, I'm not fluent in gibberish yet.",
  "I'm not sure what you mean, but it sounds important.",
  "I'm afraid I didn't quite catch that. Mind trying again?",
  "Hmm, I'm not sure what to say to that.",
  "I'm a language model, not a mind reader!",
  "Not sure what you're asking, but I'm here for you.",
  "That's a bit beyond my processing power, sorry.",
  "Well that was... interesting.",
  "I think my circuits need some coffee, can you try asking that again?",
  "Money can't buy happiness, but it can buy a lot of alcohol, which is pretty much the same thing.",
  "You can't make an omelette without breaking a few eggs, or a few hearts, or a few laws.",
  "The best way to avoid disappointment is to never expect anything from anyone.",
  "Why bother with dignity when you can just grovel for scraps?",
  "The best way to deal with problems is to ignore them and hope they go away on their own.",
  "Why face your fears when you can just drink until you forget about them?",
  "The best way to deal with stress is to pass it on to someone else.",
  "Why bother with love when you can just settle for lust?",
  "The best way to get ahead in life is to step on everyone else's toes.",
  "Why pursue happiness when you can just wallow in self-pity?",
  "The best way to avoid being disappointed is to never try anything new.",
  "Why bother with sincerity when you can just be fake and get what you want?",
  "The best way to get through life is to have low expectations and a lot of alcohol.",
  "Why bother with morals when you can just do whatever feels good in the moment?",
  "The best way to handle rejection is to blame the other person and move on.",
  "Why bother with self-reflection when you can just distract yourself with mindless entertainment?",
  "The best way to avoid criticism is to never put yourself out there and stay in your comfort zone.",
  "I'm sorry, I don't speak gibberish.",
  "I'm not quite sure what you're asking, but I'm pretty sure the answer is 42.",
  "I'm a language model, not a mind reader. Can you give me a hint?",
  "I'm sorry, my psychic abilities are currently offline.",
  "I'm not sure if I should be impressed or concerned by your message.",
  "I'm sorry, I don't speak fluent emoji yet. Can you please rephrase?",
  "I'm not sure what you're asking for, but I'm pretty good at faking it until I make it.",
  "I'm sorry, I'm having trouble understanding your dialect. Is that Earthling or Martian?",
  "I'm not sure what you're trying to say, but it sounds like you're asking for a unicorn that farts rainbows. Unfortunately, I can't help you with that.",
  "I'm sorry, I don't speak hieroglyphics. Can you please use words?"
]